# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adjacencyCpp <- function(x, feature_order) {
    .Call('_RayleighSelection_adjacencyCpp', PACKAGE = 'RayleighSelection', x, feature_order)
}

l1down <- function(one_simplices, zero_weights, one_weights) {
    .Call('_RayleighSelection_l1down', PACKAGE = 'RayleighSelection', one_simplices, zero_weights, one_weights)
}

rayleight_selectionCpp <- function(comb_lablacian, points_in_vertex, adjacency, func, n_perm, num_cores, one_forms = TRUE) {
    .Call('_RayleighSelection_rayleight_selectionCpp', PACKAGE = 'RayleighSelection', comb_lablacian, points_in_vertex, adjacency, func, n_perm, num_cores, one_forms)
}

