# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adjacencyCpp <- function(x, feature_order) {
    .Call('_RayleighSelection_adjacencyCpp', PACKAGE = 'RayleighSelection', x, feature_order)
}

l1down <- function(one_simplices) {
    .Call('_RayleighSelection_l1down', PACKAGE = 'RayleighSelection', one_simplices)
}

pushCpp <- function(v, x, perm, adjacency) {
    .Call('_RayleighSelection_pushCpp', PACKAGE = 'RayleighSelection', v, x, perm, adjacency)
}

